### ISSUE TITLE
mnist example test error

### ISSUE THREAD

**Issue by leetiantian** [liangfengsid/tensoronspark#7]
hi, I got an error when I run the test in pyspark shell:
>>> import tensorspark.example.spark_mnist as mnist
Traceback (most recent call last):
  File "stdin", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/tensorspark/example/spark_mnist.py", line 4, in <module>
AttributeError: 'module' object has no attribute 'python'

It seems that the "python" package under package "tensorflow" cannot be found.  
Line 4 in spark_mnist.py is "import tensorflow.python.framework.dtypes as dtypes". 
How to solve this problem? Thank you.

**Comment by leetiantian** [comment]
UPDATE：I have solved the problem above by changing line4 to " from tensorflow.python.framework import dtypes" and adding "train(sc=sc, user='liangfengsid', name='mnist_try', server_host='localhost', server_port=10080, sync_interval=100, batch_size=100, num_partition=1, num_epoch=2)" to spark_mnist.py and then just running this single file. 

But I encounter another error:
```
17/07/06 15:45:00 INFO spark.SparkContext: Running Spark version 2.1.1
17/07/06 15:45:01 WARN util.NativeCodeLoader: Unable to load native-hadoop libra                                                                                        ry for your platform... using builtin-java classes where applicable
17/07/06 15:45:01 INFO spark.SecurityManager: Changing view acls to: root
17/07/06 15:45:01 INFO spark.SecurityManager: Changing modify acls to: root
17/07/06 15:45:01 INFO spark.SecurityManager: Changing view acls groups to:
17/07/06 15:45:01 INFO spark.SecurityManager: Changing modify acls groups to:
17/07/06 15:45:01 INFO spark.SecurityManager: SecurityManager: authentication di                                                                                        sabled; ui acls disabled; users  with view permissions: Set(root); groups with v                                                                                        iew permissions: Set(); users  with modify permissions: Set(root); groups with m                                                                                        odify permissions: Set()
17/07/06 15:45:01 INFO util.Utils: Successfully started service 'sparkDriver' on                                                                                         port 54470.
17/07/06 15:45:01 INFO spark.SparkEnv: Registering MapOutputTracker
17/07/06 15:45:01 INFO spark.SparkEnv: Registering BlockManagerMaster
17/07/06 15:45:02 INFO storage.BlockManagerMasterEndpoint: Using org.apache.spar                                                                                        k.storage.DefaultTopologyMapper for getting topology information
17/07/06 15:45:02 INFO storage.BlockManagerMasterEndpoint: BlockManagerMasterEnd                                                                                        point up
17/07/06 15:45:02 INFO storage.DiskBlockManager: Created local directory at /tmp                                                                                        /blockmgr-ec5446bf-a003-40e6-8d99-4228d06a021a
17/07/06 15:45:02 INFO memory.MemoryStore: MemoryStore started with capacity 366                                                                                        .3 MB
17/07/06 15:45:02 INFO spark.SparkEnv: Registering OutputCommitCoordinator
17/07/06 15:45:02 INFO util.log: Logging initialized @9101ms
17/07/06 15:45:02 INFO server.Server: jetty-9.2.z-SNAPSHOT
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@4c92f220{/jobs,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@7741cb15{/jobs/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@2d586d15{/jobs/job,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@5f423964{/jobs/job/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@41ad35e{/stages,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@7d7ab9ab{/stages/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@132453d4{/stages/stage,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@5d63d1cd{/stages/stage/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@fb1791c{/stages/pool,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@272e2ea0{/stages/pool/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@16256362{/storage,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@558b25d2{/storage/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@5176dfe6{/storage/rdd,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@77ba046{/storage/rdd/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@3af8edb8{/environment,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@36d1ea80{/environment/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@51bf8a53{/executors,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@b1c79b2{/executors/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@76f4c044{/executors/threadDump,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@4fc8a1f0{/executors/threadDump/json,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@62084748{/static,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@a316352{/,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@5a1774b0{/api,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@505a8923{/jobs/job/kill,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@70c8b667{/stages/stage/kill,null,AVAILABLE,@Spark}
17/07/06 15:45:02 INFO server.ServerConnector: Started Spark@2513b620{HTTP/1.1}{                                                                                        0.0.0.0:4040}
17/07/06 15:45:02 INFO server.Server: Started @9339ms
17/07/06 15:45:02 INFO util.Utils: Successfully started service 'SparkUI' on por                                                                                        t 4040.
17/07/06 15:45:02 INFO ui.SparkUI: Bound SparkUI to 0.0.0.0, and started at http                                                                                        ://192.168.56.3:4040
17/07/06 15:45:03 INFO spark.SparkContext: Added file file:/opt/spark/spark-2.1.                                                                                        1-bin-hadoop2.7/examples/src/main/python/spark_mnist.py at file:/opt/spark/spark                                                                                        -2.1.1-bin-hadoop2.7/examples/src/main/python/spark_mnist.py with timestamp 1499                                                                                        355903082
17/07/06 15:45:03 INFO util.Utils: Copying /opt/spark/spark-2.1.1-bin-hadoop2.7/                                                                                        examples/src/main/python/spark_mnist.py to /tmp/spark-aca75d76-f3c4-4099-bbb4-01                                                                                        ca62da81fb/userFiles-79146420-6b0c-41d9-8b43-60ff001b2bcf/spark_mnist.py
17/07/06 15:45:03 INFO executor.Executor: Starting executor ID driver on host lo                                                                                        calhost
17/07/06 15:45:03 INFO util.Utils: Successfully started service 'org.apache.spar                                                                                        k.network.netty.NettyBlockTransferService' on port 35651.
17/07/06 15:45:03 INFO netty.NettyBlockTransferService: Server created on 192.16                                                                                        8.56.3:35651
17/07/06 15:45:03 INFO storage.BlockManager: Using org.apache.spark.storage.Rand                                                                                        omBlockReplicationPolicy for block replication policy
17/07/06 15:45:03 INFO storage.BlockManagerMaster: Registering BlockManager Bloc                                                                                        kManagerId(driver, 192.168.56.3, 35651, None)
17/07/06 15:45:03 INFO storage.BlockManagerMasterEndpoint: Registering block man                                                                                        ager 192.168.56.3:35651 with 366.3 MB RAM, BlockManagerId(driver, 192.168.56.3,                                                                                         35651, None)
17/07/06 15:45:03 INFO storage.BlockManagerMaster: Registered BlockManager Block                                                                                        ManagerId(driver, 192.168.56.3, 35651, None)
17/07/06 15:45:03 INFO storage.BlockManager: Initialized BlockManager: BlockMana                                                                                        gerId(driver, 192.168.56.3, 35651, None)
17/07/06 15:45:03 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHan                                                                                        dler@266ccef7{/metrics/json,null,AVAILABLE,@Spark}
17/07/06 15:45:05 INFO memory.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 283.0 KB, free 366.0 MB)
17/07/06 15:45:05 INFO memory.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 23.5 KB, free 366.0 MB)
17/07/06 15:45:05 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.168.56.3:35651 (size: 23.5 KB, free: 366.3 MB)
17/07/06 15:45:05 INFO spark.SparkContext: Created broadcast 0 from binaryFiles at NativeMethodAccessorImpl.java:0
17/07/06 15:45:05 INFO memory.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 282.7 KB, free 365.7 MB)
17/07/06 15:45:05 INFO memory.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 23.5 KB, free 365.7 MB)
17/07/06 15:45:05 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 192.168.56.3:35651 (size: 23.5 KB, free: 366.3 MB)
17/07/06 15:45:05 INFO spark.SparkContext: Created broadcast 1 from binaryFiles at NativeMethodAccessorImpl.java:0
17/07/06 15:45:06 INFO input.FileInputFormat: Total input paths to process : 1
17/07/06 15:45:06 INFO input.FileInputFormat: Total input paths to process : 1
17/07/06 15:45:06 INFO input.CombineFileInputFormat: DEBUG: Terminated node allocation with : CompletedNodes: 4, size left: 0
17/07/06 15:45:06 INFO input.FileInputFormat: Total input paths to process : 1
17/07/06 15:45:06 INFO input.FileInputFormat: Total input paths to process : 1
17/07/06 15:45:06 INFO input.CombineFileInputFormat: DEBUG: Terminated node allocation with : CompletedNodes: 4, size left: 60008
WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:170: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2017-07-06 23:45:07.673713: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 23:45:07.673867: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-06 23:45:07.673930: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/opt/spark/spark-2.1.1-bin-hadoop2.7/examples/src/main/python/spark_mnist.py", line 195, in <module>
    train(sc=sc, user='root', name='mnist_try', server_host='localhost', server_port=10080, sync_interval=100, batch_size=100, num_partition=1, num_epoch=2)
  File "/opt/spark/spark-2.1.1-bin-hadoop2.7/examples/src/main/python/spark_mnist.py", line 174, in train
    spark_sess.run(train_step, feed_rdd=image_label_rdd, feed_name_list=feed_name_list, param_list=param_list, weight_combiner=combiner, shuffle_within_partition=True, server_reusable=server_reusable)
  File "build/bdist.linux-x86_64/egg/tensorspark/core/spark_session.py", line 121, in run
  File "build/bdist.linux-x86_64/egg/tensorspark/core/spark_session.py", line 220, in broadcast_session
  File "build/bdist.linux-x86_64/egg/tensorspark/core/spark_session.py", line 254, in save_session_hdfs
  File "build/bdist.linux-x86_64/egg/tensorspark/core/hdfs_util.py", line 492, in put
IOError: [Errno 2] No such file or directory: '/tmp/session_mnist_try_1499355908429'
17/07/06 15:45:09 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/07/06 15:45:09 INFO server.ServerConnector: Stopped Spark@2513b620{HTTP/1.1}{0.0.0.0:4040}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@70c8b667{/stages/stage/kill,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@505a8923{/jobs/job/kill,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@5a1774b0{/api,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@a316352{/,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@62084748{/static,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@4fc8a1f0{/executors/threadDump/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@76f4c044{/executors/threadDump,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@b1c79b2{/executors/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@51bf8a53{/executors,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@36d1ea80{/environment/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@3af8edb8{/environment,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@77ba046{/storage/rdd/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@5176dfe6{/storage/rdd,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@558b25d2{/storage/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@16256362{/storage,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@272e2ea0{/stages/pool/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@fb1791c{/stages/pool,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@5d63d1cd{/stages/stage/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@132453d4{/stages/stage,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@7d7ab9ab{/stages/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@41ad35e{/stages,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@5f423964{/jobs/job/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@2d586d15{/jobs/job,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@7741cb15{/jobs/json,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@4c92f220{/jobs,null,UNAVAILABLE,@Spark}
17/07/06 15:45:09 INFO ui.SparkUI: Stopped Spark web UI at http://192.168.56.3:4040
17/07/06 15:45:09 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/07/06 15:45:09 INFO memory.MemoryStore: MemoryStore cleared
17/07/06 15:45:09 INFO storage.BlockManager: BlockManager stopped
17/07/06 15:45:09 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
17/07/06 15:45:09 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/07/06 15:45:09 INFO spark.SparkContext: Successfully stopped SparkContext
17/07/06 15:45:09 INFO util.ShutdownHookManager: Shutdown hook called
17/07/06 15:45:09 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-aca75d76-f3c4-4099-bbb4-01ca62da81fb
17/07/06 15:45:09 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-aca75d76-f3c4-4099-bbb4-01ca62da81fb/pyspark-ab0cd691-4a55-4f5e-b0aa-ccfe94806f02
```


The error is "IOError: [Errno 2] No such file or directory: '/tmp/session_mnist_try_1499355908429'" so I checked the /tmp directory and found the following files:
```
session_mnist_try_1499343625526.data-00000-of-00001
session_mnist_try_1499343625526.index
session_mnist_try_1499343625526.meta
session_mnist_try_1499343625526.saver.proto
session_mnist_try_1499355908429.data-00000-of-00001
session_mnist_try_1499355908429.index
session_mnist_try_1499355908429.meta
session_mnist_try_1499355908429.saver.proto
```
How to solve this problem? Looking forward to your reply.
